//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PraiseBase.Presenter.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PraiseBase.Presenter.Properties.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hinzufügen ähnelt.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weitere Informationen können im Logfile gefunden werden. ähnelt.
        /// </summary>
        public static string AdditionalDetailsCanBeFoundInLogfile {
            get {
                return ResourceManager.GetString("AdditionalDetailsCanBeFoundInLogfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alle Dateien ähnelt.
        /// </summary>
        public static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Achtung ähnelt.
        /// </summary>
        public static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abbrechen ähnelt.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kategorie ähnelt.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auf Update prüfen ähnelt.
        /// </summary>
        public static string CheckForUpdate {
            get {
                return ResourceManager.GetString("CheckForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verbindung zum Update-Server nicht möglich! ähnelt.
        /// </summary>
        public static string ConnectionToUpdateServerFailed {
            get {
                return ResourceManager.GetString("ConnectionToUpdateServerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;{0}&apos; in die Zwischenablage kopiert ähnelt.
        /// </summary>
        public static string CopiedIntoClipBoard {
            get {
                return ResourceManager.GetString("CopiedIntoClipBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erstelle Miniaturbilder ähnelt.
        /// </summary>
        public static string CreatingThumbnails {
            get {
                return ResourceManager.GetString("CreatingThumbnails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datenbankfehler ähnelt.
        /// </summary>
        public static string DatabaseError {
            get {
                return ResourceManager.GetString("DatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hat das Lied wirklich den Standardnamen &apos;{0}&apos;? ähnelt.
        /// </summary>
        public static string DoesTheSongReallyHaveTheDefaultTitle {
            get {
                return ResourceManager.GetString("DoesTheSongReallyHaveTheDefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Leere Einträge sind nicht erlaubt! ähnelt.
        /// </summary>
        public static string EmptyEntriesAreNotAllowed {
            get {
                return ResourceManager.GetString("EmptyEntriesAreNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler ähnelt.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schwerer Fehler ähnelt.
        /// </summary>
        public static string FatalError {
            get {
                return ResourceManager.GetString("FatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es ist ein schwerwiegender Fehler vom Typ &apos;{0}&apos; aufgetreten und das Programm muss beendet werden. ähnelt.
        /// </summary>
        public static string FatalErrorOccuredProgramTerminated {
            get {
                return ResourceManager.GetString("FatalErrorOccuredProgramTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Favoriten ähnelt.
        /// </summary>
        public static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Format nicht unterstüzt! ähnelt.
        /// </summary>
        public static string FormatNotSupported {
            get {
                return ResourceManager.GetString("FormatNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bilder ähnelt.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bilder importieren ähnelt.
        /// </summary>
        public static string ImportImages {
            get {
                return ResourceManager.GetString("ImportImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ungültiger Zeitraum! ähnelt.
        /// </summary>
        public static string InvalidTimeRange {
            get {
                return ResourceManager.GetString("InvalidTimeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sprache bereits vorhanden! ähnelt.
        /// </summary>
        public static string LanguageExistsAlready {
            get {
                return ResourceManager.GetString("LanguageExistsAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lied {0} geöffnet ähnelt.
        /// </summary>
        public static string LoadedSong {
            get {
                return ResourceManager.GetString("LoadedSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Treffer ähnelt.
        /// </summary>
        public static string Matches {
            get {
                return ResourceManager.GetString("Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name bereits vorhanden! ähnelt.
        /// </summary>
        public static string NameExistsAlready {
            get {
                return ResourceManager.GetString("NameExistsAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name des Liedteils ähnelt.
        /// </summary>
        public static string NameOfTheSongPart {
            get {
                return ResourceManager.GetString("NameOfTheSongPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kein aktives Lied! ähnelt.
        /// </summary>
        public static string NoActiveSong {
            get {
                return ResourceManager.GetString("NoActiveSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Bilder ausgewählt! ähnelt.
        /// </summary>
        public static string NoImagesSelected {
            get {
                return ResourceManager.GetString("NoImagesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kein zweiter Bildschirm gefunden! Der Primärbildschirm wird stattdessen verwendet. ähnelt.
        /// </summary>
        public static string NoSecondScreenFoundUsingMainScreen {
            get {
                return ResourceManager.GetString("NoSecondScreenFoundUsingMainScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es ist kein entsprechender Importer vorhanden! ähnelt.
        /// </summary>
        public static string NoSongImporterAvailable {
            get {
                return ResourceManager.GetString("NoSongImporterAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Lieder ausgewählt! ähnelt.
        /// </summary>
        public static string NoSongsSelected {
            get {
                return ResourceManager.GetString("NoSongsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nichts gefunden! ähnelt.
        /// </summary>
        public static string NothingFound {
            get {
                return ResourceManager.GetString("NothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} Lieder wurden importiert! ähnelt.
        /// </summary>
        public static string nSongsHaveBeenImported {
            get {
                return ResourceManager.GetString("nSongsHaveBeenImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PraiseBox Datenbank öffnen ähnelt.
        /// </summary>
        public static string OpenPraiseBoxDatabase {
            get {
                return ResourceManager.GetString("OpenPraiseBoxDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Setliste öffnen... ähnelt.
        /// </summary>
        public static string OpenSetlist {
            get {
                return ResourceManager.GetString("OpenSetlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lied öffnen ähnelt.
        /// </summary>
        public static string OpenSong {
            get {
                return ResourceManager.GetString("OpenSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WorshipSystem Datenbank öffnen ähnelt.
        /// </summary>
        public static string OpenWorshipSystemDatabase {
            get {
                return ResourceManager.GetString("OpenWorshipSystemDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anderer Name ähnelt.
        /// </summary>
        public static string OtherName {
            get {
                return ResourceManager.GetString("OtherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Überschreiben ähnelt.
        /// </summary>
        public static string Overwrite {
            get {
                return ResourceManager.GetString("Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte melde diesen Fehler dem Entwickler, indem du auf den &apos;Hilfe&apos;-Button klickst. ähnelt.
        /// </summary>
        public static string PleaseReportBugToDeveloperByClickingOnHelpButton {
            get {
                return ResourceManager.GetString("PleaseReportBugToDeveloperByClickingOnHelpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eine Instanz dieser Software läuft bereits! ähnelt.
        /// </summary>
        public static string ProgramInstanceAlreadyRunning {
            get {
                return ResourceManager.GetString("ProgramInstanceAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sie haben die aktuellste Version! ähnelt.
        /// </summary>
        public static string ProgramVersionUptodate {
            get {
                return ResourceManager.GetString("ProgramVersionUptodate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projektion ähnelt.
        /// </summary>
        public static string Projection {
            get {
                return ResourceManager.GetString("Projection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Folie wirklich löschen? ähnelt.
        /// </summary>
        public static string ReallyDeleteSlide {
            get {
                return ResourceManager.GetString("ReallyDeleteSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Liedteil wirklich löschen? ähnelt.
        /// </summary>
        public static string ReallyDeleteSongPart {
            get {
                return ResourceManager.GetString("ReallyDeleteSongPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Setliste wirklich leeren? ähnelt.
        /// </summary>
        public static string ReallyEmptySetlist {
            get {
                return ResourceManager.GetString("ReallyEmptySetlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sollen die Standardwerte wirklich geladen werden? ähnelt.
        /// </summary>
        public static string ReallyResetFactoryDefaults {
            get {
                return ResourceManager.GetString("ReallyResetFactoryDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zurücksetzen ähnelt.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Willst du die Änderungen im Lied &apos;{0}&apos; speichern? ähnelt.
        /// </summary>
        public static string SaveChangesMadeToTheSong {
            get {
                return ResourceManager.GetString("SaveChangesMadeToTheSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Setliste speichern unter... ähnelt.
        /// </summary>
        public static string SaveSetlistAs {
            get {
                return ResourceManager.GetString("SaveSetlistAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lied speichern unter... ähnelt.
        /// </summary>
        public static string SaveSongAs {
            get {
                return ResourceManager.GetString("SaveSongAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suchergebnisse ähnelt.
        /// </summary>
        public static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PraiseBase-Presenter Setliste ähnelt.
        /// </summary>
        public static string SetlistFile {
            get {
                return ResourceManager.GetString("SetlistFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soll die aktuelle Setliste gespeichert werden? ähnelt.
        /// </summary>
        public static string ShouldCurrentSetlistBeSaved {
            get {
                return ResourceManager.GetString("ShouldCurrentSetlistBeSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ablauf ähnelt.
        /// </summary>
        public static string ShowSongSequence {
            get {
                return ResourceManager.GetString("ShowSongSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Struktur ähnelt.
        /// </summary>
        public static string ShowSongStructure {
            get {
                return ResourceManager.GetString("ShowSongStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Slide ähnelt.
        /// </summary>
        public static string Slide {
            get {
                return ResourceManager.GetString("Slide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Liederbrowser ähnelt.
        /// </summary>
        public static string SongBrowser {
            get {
                return ResourceManager.GetString("SongBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Lied kann leider nicht in diesem Format gespeichert werden! Bitte wähle ein anderes Dateiformat! ähnelt.
        /// </summary>
        public static string SongCannotBeSavedInThisFormat {
            get {
                return ResourceManager.GetString("SongCannotBeSavedInThisFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Lied {0} existiert nicht! ähnelt.
        /// </summary>
        public static string SongDoesNotExist {
            get {
                return ResourceManager.GetString("SongDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dieses Lied existiert nicht mehr in der Liederliste! ähnelt.
        /// </summary>
        public static string SongDoesNotExistInSonglist {
            get {
                return ResourceManager.GetString("SongDoesNotExistInSonglist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Liededitor ähnelt.
        /// </summary>
        public static string SongEditor {
            get {
                return ResourceManager.GetString("SongEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Übersetzung deaktivieren ähnelt.
        /// </summary>
        public static string SongEditorChild_EnableTranslation_Disable_translation {
            get {
                return ResourceManager.GetString("SongEditorChild_EnableTranslation_Disable_translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soll die Übersetzung entfernt werden? ähnelt.
        /// </summary>
        public static string SongEditorChild_EnableTranslation_Should_Translation_be_removed {
            get {
                return ResourceManager.GetString("SongEditorChild_EnableTranslation_Should_Translation_be_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Lied {0}&apos; existiert bereits! ähnelt.
        /// </summary>
        public static string SongExistsAlready {
            get {
                return ResourceManager.GetString("SongExistsAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Diese Lieddatei ist leider fehlerhaft! ähnelt.
        /// </summary>
        public static string SongFileHasErrors {
            get {
                return ResourceManager.GetString("SongFileHasErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dieses Dateiformat wird leider nicht unterstüzt! ähnelt.
        /// </summary>
        public static string SongFormatNotSupported {
            get {
                return ResourceManager.GetString("SongFormatNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lied &apos;{0}&apos; aktualisiert ähnelt.
        /// </summary>
        public static string SongHasBeenUpdated {
            get {
                return ResourceManager.GetString("SongHasBeenUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Liederimport ähnelt.
        /// </summary>
        public static string SongImporter {
            get {
                return ResourceManager.GetString("SongImporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Lied muss mindestens einen Liedteil haben! ähnelt.
        /// </summary>
        public static string SongNeedsAtLeastOneSongPart {
            get {
                return ResourceManager.GetString("SongNeedsAtLeastOneSongPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dieser Liedteil existiert bereits! ähnelt.
        /// </summary>
        public static string SongPartExistsAlready {
            get {
                return ResourceManager.GetString("SongPartExistsAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Liedteil muss mindestens eine Folie haben! ähnelt.
        /// </summary>
        public static string SongPartsNeedsAtLeastOneSlide {
            get {
                return ResourceManager.GetString("SongPartsNeedsAtLeastOneSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lied gespeichert als {0} ähnelt.
        /// </summary>
        public static string SongSavedAs {
            get {
                return ResourceManager.GetString("SongSavedAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lieder: {0} ähnelt.
        /// </summary>
        public static string SongsCount {
            get {
                return ResourceManager.GetString("SongsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} Lieder wurden importiert! ähnelt.
        /// </summary>
        public static string SongsImported {
            get {
                return ResourceManager.GetString("SongsImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entschuldigung ähnelt.
        /// </summary>
        public static string Sorry {
            get {
                return ResourceManager.GetString("Sorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Diaschau starten ähnelt.
        /// </summary>
        public static string StartSlideshow {
            get {
                return ResourceManager.GetString("StartSlideshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Diaschau stoppen ähnelt.
        /// </summary>
        public static string StopSlideshow {
            get {
                return ResourceManager.GetString("StopSlideshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tag bereits vorhanden! ähnelt.
        /// </summary>
        public static string TagExistsAlready {
            get {
                return ResourceManager.GetString("TagExistsAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Miniaturbilder ähnelt.
        /// </summary>
        public static string Thumbnails {
            get {
                return ResourceManager.GetString("Thumbnails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zeitraum: {0} - {1} ähnelt.
        /// </summary>
        public static string TimeRangeFromTo {
            get {
                return ResourceManager.GetString("TimeRangeFromTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hauptverzeichnis ähnelt.
        /// </summary>
        public static string TopDirectory {
            get {
                return ResourceManager.GetString("TopDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das letzte Element kann nicht entfernt werden! ähnelt.
        /// </summary>
        public static string UnableToRemoveLastElement {
            get {
                return ResourceManager.GetString("UnableToRemoveLastElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein Update auf Version {0} ist verfügbar (Sie haben Version {1}). ähnelt.
        /// </summary>
        public static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zefania XML Bibeldateien ähnelt.
        /// </summary>
        public static string ZefaniaXmlBibleFiles {
            get {
                return ResourceManager.GetString("ZefaniaXmlBibleFiles", resourceCulture);
            }
        }
    }
}
