//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pbp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pbp.Properties.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinzufügen.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achtung.
        /// </summary>
        internal static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbindung zum Update-Server nicht möglich!.
        /// </summary>
        internal static string ConnectionToUpdateServerFailed {
            get {
                return ResourceManager.GetString("ConnectionToUpdateServerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstelle Miniaturbilder.
        /// </summary>
        internal static string CreatingThumbnails {
            get {
                return ResourceManager.GetString("CreatingThumbnails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datenbankfehler.
        /// </summary>
        internal static string DatabaseError {
            get {
                return ResourceManager.GetString("DatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hat das Lied wirklich den Standardnamen &apos;{0}&apos;?.
        /// </summary>
        internal static string DoesTheSongReallyHaveTheDefaultTitle {
            get {
                return ResourceManager.GetString("DoesTheSongReallyHaveTheDefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leere Einträge sind nicht erlaubt!.
        /// </summary>
        internal static string EmptyEntriesAreNotAllowed {
            get {
                return ResourceManager.GetString("EmptyEntriesAreNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favoriten.
        /// </summary>
        internal static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format nicht unterstüzt!.
        /// </summary>
        internal static string FormatNotSupported {
            get {
                return ResourceManager.GetString("FormatNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilder.
        /// </summary>
        internal static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache bereits vorhanden!.
        /// </summary>
        internal static string LanguageExistsAlready {
            get {
                return ResourceManager.GetString("LanguageExistsAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lied {0} geöffnet.
        /// </summary>
        internal static string LoadedSong {
            get {
                return ResourceManager.GetString("LoadedSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name bereits vorhanden!.
        /// </summary>
        internal static string NameExistsAlready {
            get {
                return ResourceManager.GetString("NameExistsAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name des Liedteils.
        /// </summary>
        internal static string NameOfTheSongPart {
            get {
                return ResourceManager.GetString("NameOfTheSongPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kein aktives Lied!.
        /// </summary>
        internal static string NoActiveSong {
            get {
                return ResourceManager.GetString("NoActiveSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Bilder ausgewählt!.
        /// </summary>
        internal static string NoImagesSelected {
            get {
                return ResourceManager.GetString("NoImagesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kein zweiter Bildschirm gefunden! Der Primärbildschirm wird stattdessen verwendet..
        /// </summary>
        internal static string NoSecondScreenFoundUsingMainScreen {
            get {
                return ResourceManager.GetString("NoSecondScreenFoundUsingMainScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist kein entsprechender Importer vorhanden!.
        /// </summary>
        internal static string NoSongImporterAvailable {
            get {
                return ResourceManager.GetString("NoSongImporterAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Lieder ausgewählt!.
        /// </summary>
        internal static string NoSongsSelected {
            get {
                return ResourceManager.GetString("NoSongsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nichts gefunden!.
        /// </summary>
        internal static string NothingFound {
            get {
                return ResourceManager.GetString("NothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PraiseBox Datenbank öffnen.
        /// </summary>
        internal static string OpenPraiseBoxDatabase {
            get {
                return ResourceManager.GetString("OpenPraiseBoxDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setliste öffnen....
        /// </summary>
        internal static string OpenSetlist {
            get {
                return ResourceManager.GetString("OpenSetlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lied öffnen.
        /// </summary>
        internal static string OpenSong {
            get {
                return ResourceManager.GetString("OpenSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorshipSystem Datenbank öffnen.
        /// </summary>
        internal static string OpenWorshipSystemDatabase {
            get {
                return ResourceManager.GetString("OpenWorshipSystemDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anderer Name.
        /// </summary>
        internal static string OtherName {
            get {
                return ResourceManager.GetString("OtherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überschreiben.
        /// </summary>
        internal static string Overwrite {
            get {
                return ResourceManager.GetString("Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine Instanz dieser Software läuft bereits!.
        /// </summary>
        internal static string ProgramInstanceAlreadyRunning {
            get {
                return ResourceManager.GetString("ProgramInstanceAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie haben die aktuellste Version!.
        /// </summary>
        internal static string ProgramVersionUptodate {
            get {
                return ResourceManager.GetString("ProgramVersionUptodate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projektion.
        /// </summary>
        internal static string Projection {
            get {
                return ResourceManager.GetString("Projection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folie wirklich löschen?.
        /// </summary>
        internal static string ReallyDeleteSlide {
            get {
                return ResourceManager.GetString("ReallyDeleteSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liedteil wirklich löschen?.
        /// </summary>
        internal static string ReallyDeleteSongPart {
            get {
                return ResourceManager.GetString("ReallyDeleteSongPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setliste wirklich leeren?.
        /// </summary>
        internal static string ReallyEmptySetlist {
            get {
                return ResourceManager.GetString("ReallyEmptySetlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sollen die Standardwerte wirklich geladen werden?.
        /// </summary>
        internal static string ReallyResetFactoryDefaults {
            get {
                return ResourceManager.GetString("ReallyResetFactoryDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurücksetzen.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willst du die Änderungen im Lied &apos;{0}&apos; speichern?.
        /// </summary>
        internal static string SaveChangesMadeToTheSong {
            get {
                return ResourceManager.GetString("SaveChangesMadeToTheSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setliste speichern unter....
        /// </summary>
        internal static string SaveSetlistAs {
            get {
                return ResourceManager.GetString("SaveSetlistAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lied speichern unter....
        /// </summary>
        internal static string SaveSongAs {
            get {
                return ResourceManager.GetString("SaveSongAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suchergebnisse.
        /// </summary>
        internal static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PraiseBase-Presenter Setliste.
        /// </summary>
        internal static string SetlistFile {
            get {
                return ResourceManager.GetString("SetlistFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide.
        /// </summary>
        internal static string Slide {
            get {
                return ResourceManager.GetString("Slide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liederbrowser.
        /// </summary>
        internal static string SongBrowser {
            get {
                return ResourceManager.GetString("SongBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Lied kann leider nicht in diesem Format gespeichert werden! Bitte wähle ein anderes Dateiformat!.
        /// </summary>
        internal static string SongCannotBeSavedInThisFormat {
            get {
                return ResourceManager.GetString("SongCannotBeSavedInThisFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Lied {0} existiert nicht!.
        /// </summary>
        internal static string SongDoesNotExist {
            get {
                return ResourceManager.GetString("SongDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieses Lied existiert nicht mehr in der Liederliste!.
        /// </summary>
        internal static string SongDoesNotExistInSonglist {
            get {
                return ResourceManager.GetString("SongDoesNotExistInSonglist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liededitor.
        /// </summary>
        internal static string SongEditor {
            get {
                return ResourceManager.GetString("SongEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Lied {0}&apos; existiert bereits!.
        /// </summary>
        internal static string SongExistsAlready {
            get {
                return ResourceManager.GetString("SongExistsAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Lieddatei ist leider fehlerhaft!.
        /// </summary>
        internal static string SongFileHasErrors {
            get {
                return ResourceManager.GetString("SongFileHasErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieses Dateiformat wird leider nicht unterstüzt!.
        /// </summary>
        internal static string SongFormatNotSupported {
            get {
                return ResourceManager.GetString("SongFormatNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liederimport.
        /// </summary>
        internal static string SongImporter {
            get {
                return ResourceManager.GetString("SongImporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Lied muss mindestens einen Liedteil haben!.
        /// </summary>
        internal static string SongNeedsAtLeastOneSongPart {
            get {
                return ResourceManager.GetString("SongNeedsAtLeastOneSongPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Liedteil muss mindestens eine Folie haben!.
        /// </summary>
        internal static string SongPartsNeedsAtLeastOneSlide {
            get {
                return ResourceManager.GetString("SongPartsNeedsAtLeastOneSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lied gespeichert als {0}.
        /// </summary>
        internal static string SongSavedAs {
            get {
                return ResourceManager.GetString("SongSavedAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Lieder wurden importiert!.
        /// </summary>
        internal static string SongsImported {
            get {
                return ResourceManager.GetString("SongsImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entschuldigung.
        /// </summary>
        internal static string Sorry {
            get {
                return ResourceManager.GetString("Sorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diaschau starten.
        /// </summary>
        internal static string StartSlideshow {
            get {
                return ResourceManager.GetString("StartSlideshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diaschau stoppen.
        /// </summary>
        internal static string StopSlideshow {
            get {
                return ResourceManager.GetString("StopSlideshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag bereits vorhanden!.
        /// </summary>
        internal static string TagExistsAlready {
            get {
                return ResourceManager.GetString("TagExistsAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Update auf Version {0} ist verfügbar!.
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
    }
}
