//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PraiseBase.Presenter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PraiseBase.Presenter.Properties.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinzufügen.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weitere Informationen können im Logfile gefunden werden..
        /// </summary>
        public static string AdditionalDetailsCanBeFoundInLogfile {
            get {
                return ResourceManager.GetString("AdditionalDetailsCanBeFoundInLogfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Dateien.
        /// </summary>
        public static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achtung.
        /// </summary>
        public static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auf Update prüfen.
        /// </summary>
        public static string CheckForUpdate {
            get {
                return ResourceManager.GetString("CheckForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbindung zum Update-Server nicht möglich!.
        /// </summary>
        public static string ConnectionToUpdateServerFailed {
            get {
                return ResourceManager.GetString("ConnectionToUpdateServerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; in die Zwischenablage kopiert.
        /// </summary>
        public static string CopiedIntoClipBoard {
            get {
                return ResourceManager.GetString("CopiedIntoClipBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstelle Miniaturbilder.
        /// </summary>
        public static string CreatingThumbnails {
            get {
                return ResourceManager.GetString("CreatingThumbnails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datenbankfehler.
        /// </summary>
        public static string DatabaseError {
            get {
                return ResourceManager.GetString("DatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hat das Lied wirklich den Standardnamen &apos;{0}&apos;?.
        /// </summary>
        public static string DoesTheSongReallyHaveTheDefaultTitle {
            get {
                return ResourceManager.GetString("DoesTheSongReallyHaveTheDefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leere Einträge sind nicht erlaubt!.
        /// </summary>
        public static string EmptyEntriesAreNotAllowed {
            get {
                return ResourceManager.GetString("EmptyEntriesAreNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schwerer Fehler.
        /// </summary>
        public static string FatalError {
            get {
                return ResourceManager.GetString("FatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist ein schwerwiegender Fehler vom Typ &apos;{0}&apos; aufgetreten und das Programm muss beendet werden..
        /// </summary>
        public static string FatalErrorOccuredProgramTerminated {
            get {
                return ResourceManager.GetString("FatalErrorOccuredProgramTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favoriten.
        /// </summary>
        public static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format nicht unterstüzt!.
        /// </summary>
        public static string FormatNotSupported {
            get {
                return ResourceManager.GetString("FormatNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilder.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültiger Zeitraum!.
        /// </summary>
        public static string InvalidTimeRange {
            get {
                return ResourceManager.GetString("InvalidTimeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache bereits vorhanden!.
        /// </summary>
        public static string LanguageExistsAlready {
            get {
                return ResourceManager.GetString("LanguageExistsAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lied {0} geöffnet.
        /// </summary>
        public static string LoadedSong {
            get {
                return ResourceManager.GetString("LoadedSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treffer.
        /// </summary>
        public static string Matches {
            get {
                return ResourceManager.GetString("Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name bereits vorhanden!.
        /// </summary>
        public static string NameExistsAlready {
            get {
                return ResourceManager.GetString("NameExistsAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name des Liedteils.
        /// </summary>
        public static string NameOfTheSongPart {
            get {
                return ResourceManager.GetString("NameOfTheSongPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kein aktives Lied!.
        /// </summary>
        public static string NoActiveSong {
            get {
                return ResourceManager.GetString("NoActiveSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Bilder ausgewählt!.
        /// </summary>
        public static string NoImagesSelected {
            get {
                return ResourceManager.GetString("NoImagesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kein zweiter Bildschirm gefunden! Der Primärbildschirm wird stattdessen verwendet..
        /// </summary>
        public static string NoSecondScreenFoundUsingMainScreen {
            get {
                return ResourceManager.GetString("NoSecondScreenFoundUsingMainScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist kein entsprechender Importer vorhanden!.
        /// </summary>
        public static string NoSongImporterAvailable {
            get {
                return ResourceManager.GetString("NoSongImporterAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Lieder ausgewählt!.
        /// </summary>
        public static string NoSongsSelected {
            get {
                return ResourceManager.GetString("NoSongsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nichts gefunden!.
        /// </summary>
        public static string NothingFound {
            get {
                return ResourceManager.GetString("NothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Lieder wurden importiert!.
        /// </summary>
        public static string nSongsHaveBeenImported {
            get {
                return ResourceManager.GetString("nSongsHaveBeenImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PraiseBox Datenbank öffnen.
        /// </summary>
        public static string OpenPraiseBoxDatabase {
            get {
                return ResourceManager.GetString("OpenPraiseBoxDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setliste öffnen....
        /// </summary>
        public static string OpenSetlist {
            get {
                return ResourceManager.GetString("OpenSetlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lied öffnen.
        /// </summary>
        public static string OpenSong {
            get {
                return ResourceManager.GetString("OpenSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorshipSystem Datenbank öffnen.
        /// </summary>
        public static string OpenWorshipSystemDatabase {
            get {
                return ResourceManager.GetString("OpenWorshipSystemDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anderer Name.
        /// </summary>
        public static string OtherName {
            get {
                return ResourceManager.GetString("OtherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überschreiben.
        /// </summary>
        public static string Overwrite {
            get {
                return ResourceManager.GetString("Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte melde diesen Fehler dem Entwickler, indem du auf den &apos;Hilfe&apos;-Button klickst..
        /// </summary>
        public static string PleaseReportBugToDeveloperByClickingOnHelpButton {
            get {
                return ResourceManager.GetString("PleaseReportBugToDeveloperByClickingOnHelpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine Instanz dieser Software läuft bereits!.
        /// </summary>
        public static string ProgramInstanceAlreadyRunning {
            get {
                return ResourceManager.GetString("ProgramInstanceAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie haben die aktuellste Version!.
        /// </summary>
        public static string ProgramVersionUptodate {
            get {
                return ResourceManager.GetString("ProgramVersionUptodate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projektion.
        /// </summary>
        public static string Projection {
            get {
                return ResourceManager.GetString("Projection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folie wirklich löschen?.
        /// </summary>
        public static string ReallyDeleteSlide {
            get {
                return ResourceManager.GetString("ReallyDeleteSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liedteil wirklich löschen?.
        /// </summary>
        public static string ReallyDeleteSongPart {
            get {
                return ResourceManager.GetString("ReallyDeleteSongPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setliste wirklich leeren?.
        /// </summary>
        public static string ReallyEmptySetlist {
            get {
                return ResourceManager.GetString("ReallyEmptySetlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sollen die Standardwerte wirklich geladen werden?.
        /// </summary>
        public static string ReallyResetFactoryDefaults {
            get {
                return ResourceManager.GetString("ReallyResetFactoryDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurücksetzen.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willst du die Änderungen im Lied &apos;{0}&apos; speichern?.
        /// </summary>
        public static string SaveChangesMadeToTheSong {
            get {
                return ResourceManager.GetString("SaveChangesMadeToTheSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setliste speichern unter....
        /// </summary>
        public static string SaveSetlistAs {
            get {
                return ResourceManager.GetString("SaveSetlistAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lied speichern unter....
        /// </summary>
        public static string SaveSongAs {
            get {
                return ResourceManager.GetString("SaveSongAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suchergebnisse.
        /// </summary>
        public static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PraiseBase-Presenter Setliste.
        /// </summary>
        public static string SetlistFile {
            get {
                return ResourceManager.GetString("SetlistFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soll die aktuelle Setliste gespeichert werden?.
        /// </summary>
        public static string ShouldCurrentSetlistBeSaved {
            get {
                return ResourceManager.GetString("ShouldCurrentSetlistBeSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ablauf.
        /// </summary>
        public static string ShowSongSequence {
            get {
                return ResourceManager.GetString("ShowSongSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Struktur.
        /// </summary>
        public static string ShowSongStructure {
            get {
                return ResourceManager.GetString("ShowSongStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide.
        /// </summary>
        public static string Slide {
            get {
                return ResourceManager.GetString("Slide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liederbrowser.
        /// </summary>
        public static string SongBrowser {
            get {
                return ResourceManager.GetString("SongBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Lied kann leider nicht in diesem Format gespeichert werden! Bitte wähle ein anderes Dateiformat!.
        /// </summary>
        public static string SongCannotBeSavedInThisFormat {
            get {
                return ResourceManager.GetString("SongCannotBeSavedInThisFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Lied {0} existiert nicht!.
        /// </summary>
        public static string SongDoesNotExist {
            get {
                return ResourceManager.GetString("SongDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieses Lied existiert nicht mehr in der Liederliste!.
        /// </summary>
        public static string SongDoesNotExistInSonglist {
            get {
                return ResourceManager.GetString("SongDoesNotExistInSonglist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liededitor.
        /// </summary>
        public static string SongEditor {
            get {
                return ResourceManager.GetString("SongEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Übersetzung deaktivieren.
        /// </summary>
        public static string SongEditorChild_EnableTranslation_Disable_translation {
            get {
                return ResourceManager.GetString("SongEditorChild_EnableTranslation_Disable_translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soll die Übersetzung entfernt werden?.
        /// </summary>
        public static string SongEditorChild_EnableTranslation_Should_Translation_be_removed {
            get {
                return ResourceManager.GetString("SongEditorChild_EnableTranslation_Should_Translation_be_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Lied {0}&apos; existiert bereits!.
        /// </summary>
        public static string SongExistsAlready {
            get {
                return ResourceManager.GetString("SongExistsAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Lieddatei ist leider fehlerhaft!.
        /// </summary>
        public static string SongFileHasErrors {
            get {
                return ResourceManager.GetString("SongFileHasErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieses Dateiformat wird leider nicht unterstüzt!.
        /// </summary>
        public static string SongFormatNotSupported {
            get {
                return ResourceManager.GetString("SongFormatNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lied &apos;{0}&apos; aktualisiert.
        /// </summary>
        public static string SongHasBeenUpdated {
            get {
                return ResourceManager.GetString("SongHasBeenUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liederimport.
        /// </summary>
        public static string SongImporter {
            get {
                return ResourceManager.GetString("SongImporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Lied muss mindestens einen Liedteil haben!.
        /// </summary>
        public static string SongNeedsAtLeastOneSongPart {
            get {
                return ResourceManager.GetString("SongNeedsAtLeastOneSongPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieser Liedteil existiert bereits!.
        /// </summary>
        public static string SongPartExistsAlready {
            get {
                return ResourceManager.GetString("SongPartExistsAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Liedteil muss mindestens eine Folie haben!.
        /// </summary>
        public static string SongPartsNeedsAtLeastOneSlide {
            get {
                return ResourceManager.GetString("SongPartsNeedsAtLeastOneSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lied gespeichert als {0}.
        /// </summary>
        public static string SongSavedAs {
            get {
                return ResourceManager.GetString("SongSavedAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lieder: {0}.
        /// </summary>
        public static string SongsCount {
            get {
                return ResourceManager.GetString("SongsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Lieder wurden importiert!.
        /// </summary>
        public static string SongsImported {
            get {
                return ResourceManager.GetString("SongsImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entschuldigung.
        /// </summary>
        public static string Sorry {
            get {
                return ResourceManager.GetString("Sorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diaschau starten.
        /// </summary>
        public static string StartSlideshow {
            get {
                return ResourceManager.GetString("StartSlideshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diaschau stoppen.
        /// </summary>
        public static string StopSlideshow {
            get {
                return ResourceManager.GetString("StopSlideshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag bereits vorhanden!.
        /// </summary>
        public static string TagExistsAlready {
            get {
                return ResourceManager.GetString("TagExistsAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miniaturbilder.
        /// </summary>
        public static string Thumbnails {
            get {
                return ResourceManager.GetString("Thumbnails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeitraum: {0} - {1}.
        /// </summary>
        public static string TimeRangeFromTo {
            get {
                return ResourceManager.GetString("TimeRangeFromTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hauptverzeichnis.
        /// </summary>
        public static string TopDirectory {
            get {
                return ResourceManager.GetString("TopDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das letzte Element kann nicht entfernt werden!.
        /// </summary>
        public static string UnableToRemoveLastElement {
            get {
                return ResourceManager.GetString("UnableToRemoveLastElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Update auf Version {0} ist verfügbar (Sie haben Version {1})..
        /// </summary>
        public static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
    }
}
