//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pbp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string dataDirectory {
            get {
                return ((string)(this["dataDirectory"]));
            }
            set {
                this["dataDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Calibri, 60pt, style=Bold")]
        public global::System.Drawing.Font projectionFont {
            get {
                return ((global::System.Drawing.Font)(this["projectionFont"]));
            }
            set {
                this["projectionFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color projectionBackColor {
            get {
                return ((global::System.Drawing.Color)(this["projectionBackColor"]));
            }
            set {
                this["projectionBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color projectionForeColor {
            get {
                return ((global::System.Drawing.Color)(this["projectionForeColor"]));
            }
            set {
                this["projectionForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color projectionFontBorderColor {
            get {
                return ((global::System.Drawing.Color)(this["projectionFontBorderColor"]));
            }
            set {
                this["projectionFontBorderColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool projectionFontScaling {
            get {
                return ((bool)(this["projectionFontScaling"]));
            }
            set {
                this["projectionFontScaling"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int projectionPadding {
            get {
                return ((int)(this["projectionPadding"]));
            }
            set {
                this["projectionPadding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Deutsch</string>
  <string>Englisch</string>
  <string>Französisch</string>
  <string>Italienisch</string>
  <string>Schweizerdeutsch</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection languages {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["languages"]));
            }
            set {
                this["languages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Lobpreis</string>
  <string>Anbetung</string>
  <string>Trost</string>
  <string>Hingabe</string>
  <string>Heiliger Geist</string>
  <string>Segen</string>
  <string>Dank</string>
  <string>Bitte</string>
  <string>Evangelisation</string>
  <string>Vertrauen</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection tags {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["tags"]));
            }
            set {
                this["tags"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Refrain</string>
  <string>Strophe 1</string>
  <string>Strophe 2</string>
  <string>Strophe 3</string>
  <string>Teil 1</string>
  <string>Teil 2</string>
  <string>Teil 3</string>
  <string>Instrumentalteil</string>
  <string>Bridge</string>
  <string>Schluss</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection songParts {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["songParts"]));
            }
            set {
                this["songParts"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("songs")]
        public string songDir {
            get {
                return ((string)(this["songDir"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("backgrounds")]
        public string imageDir {
            get {
                return ((string)(this["imageDir"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Praisebase Presenter")]
        public string dataDirDefaultName {
            get {
                return ((string)(this["dataDirDefaultName"]));
            }
        }
    }
}
